version: '3.8'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - APP_DB_USER=test_user
      - APP_DB_PASS=test_pass
      - APP_DB_NAME=test
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./test-db-init:/docker-entrypoint-initdb.d/

volumes:
  db:
    driver: local